_version: 31
anticheat:
  anti-xray:
    enabled: true
    engine-mode: 1
    hidden-blocks:
    - copper_ore
    - deepslate_copper_ore
    - raw_copper_block
    - gold_ore
    - deepslate_gold_ore
    - iron_ore
    - deepslate_iron_ore
    - raw_iron_block
    - coal_ore
    - deepslate_coal_ore
    - lapis_ore
    - deepslate_lapis_ore
    - mossy_cobblestone
    - obsidian
    - chest
    - diamond_ore
    - deepslate_diamond_ore
    - redstone_ore
    - deepslate_redstone_ore
    - clay
    - emerald_ore
    - deepslate_emerald_ore
    - ender_chest
    lava-obscures: false
    max-block-height: 64
    replacement-blocks:
    - stone
    - oak_planks
    - deepslate
    update-radius: 1
    use-permission: false
chunks:
  auto-save-interval: 6000
  delay-chunk-unloads-by: 5s
  entity-per-chunk-save-limit:
    arrow: 80
    ender_pearl: 80
    experience_orb: 80
    fireball: 80
    small_fireball: 80
    snowball: 80
  fixed-chunk-inhabited-time: 10000
  flush-regions-on-save: true
  max-auto-save-chunks-per-tick: 8
  prevent-moving-into-unloaded-chunks: true
collisions:
  allow-player-cramming-damage: false
  allow-vehicle-collisions: false
  fix-climbing-bypassing-cramming-rule: true
  max-entity-collisions: 3
  only-players-collide: true
command-blocks:
  force-follow-perm-level: true
  permissions-level: 2
entities:
  armor-stands:
    do-collision-entity-lookups: false
    tick: false
  behavior:
    allow-spider-world-border-climbing: false
    baby-zombie-movement-modifier: 0.4
    disable-chest-cat-detection: true
    disable-creeper-lingering-effect: true
    disable-player-crits: false
    door-breaking-difficulty:
      husk:
      - HARD
      vindicator:
      - NORMAL
      - HARD
      zombie:
      - HARD
      zombie_villager:
      - HARD
      zombified_piglin:
      - HARD
    ender-dragons-death-always-places-dragon-egg: false
    experience-merge-max-value: 80
    mobs-can-always-pick-up-loot:
      skeletons: false
      zombies: false
    nerf-pigmen-from-nether-portals: true
    only-merge-items-horizontally: true
    parrots-are-unaffected-by-player-movement: true
    phantoms-do-not-spawn-on-creative-players: true
    phantoms-only-attack-insomniacs: true
    phantoms-spawn-attempt-max-seconds: 100
    phantoms-spawn-attempt-min-seconds: 60
    piglins-guard-chests: true
    pillager-patrols:
      disable: true
      spawn-chance: 0.1
      spawn-delay:
        per-player: false
        ticks: 12000
      start:
        day: 5
        per-player: false
    player-insomnia-start-ticks: 72000
    should-remove-dragon: false
    spawner-nerfed-mobs-should-jump: false
    zombie-villager-infection-chance: default
    zombies-target-turtle-eggs: true
  entities-target-with-follow-range: false
  markers:
    tick: false
  mob-effects:
    immune-to-wither-effect:
      wither: true
      wither-skeleton: true
    spiders-immune-to-poison-effect: true
  sniffer:
    boosted-hatch-time: default
    hatch-time: default
  spawning:
    all-chunks-are-slime-chunks: false
    alt-item-despawn-rate:
      enabled: true
      items:
        cobblestone: 300
    count-all-mobs-for-spawning: false
    creative-arrow-despawn-rate: 20
    despawn-range-shape: ELLIPSOID
    despawn-ranges:
      ambient:
        hard: 32
        soft: 20
      axolotls:
        hard: 32
        soft: 20
      creature:
        hard: 32
        soft: 20
      misc:
        hard: 32
        soft: 20
      monster:
        hard: 30
        soft: 20
      underground_water_creature:
        hard: 32
        soft: 20
      water_ambient:
        hard: 32
        soft: 20
      water_creature:
        hard: 32
        soft: 20
    disable-mob-spawner-spawn-egg-transformation: true
    duplicate-uuid:
      mode: SAFE_REGEN
      safe-regen-delete-range: 32
    filter-bad-tile-entity-nbt-from-falling-blocks: true
    filtered-entity-tag-nbt-paths:
    - Pos
    - Motion
    - SleepingX
    - SleepingY
    - SleepingZ
    iron-golems-can-spawn-in-air: false
    monster-spawn-max-light-level: 6
    non-player-arrow-despawn-rate: 15
    per-player-mob-spawns: false
    scan-for-legacy-ender-dragon: true
    skeleton-horse-thunder-spawn-chance: 0.005
    slime-spawn-height:
      slime-chunk:
        maximum: 40.0
      surface-biome:
        maximum: 70.0
        minimum: 50.0
    spawn-limits:
      ambient: 1
      axolotls: 1
      creature: 8
      monster: 25
      underground_water_creature: 2
      water_ambient: 1
      water_creature: 2
    ticks-per-spawn:
      ambient: 500
      axolotls: 500
      creature: 500
      monster: 1
      underground_water_creature: 500
      water_ambient: 500
      water_creature: 500
    wandering-trader:
      spawn-chance-failure-increment: 15
      spawn-chance-max: 70
      spawn-chance-min: 20
      spawn-day-length: 24000
      spawn-minute-length: 1200
    wateranimal-spawn-height:
      maximum: 62
      minimum: 45
  tracking-range-y:
    animal: default
    display: default
    enabled: false
    misc: default
    monster: default
    other: default
    player: default
environment:
  disable-explosion-knockback: false
  disable-ice-and-snow: true
  disable-teleportation-suffocation-check: false
  disable-thunder: true
  fire-tick-delay: 50
  frosted-ice:
    delay:
      max: 40
      min: 20
    enabled: true
  generate-flat-bedrock: true
  locate-structures-outside-world-border: false
  max-block-ticks: 65536
  max-fluid-ticks: 65536
  nether-ceiling-void-damage-height: disabled
  optimize-explosions: true
  portal-create-radius: 16
  portal-search-radius: 128
  portal-search-vanilla-dimension-scaling: true
  treasure-maps:
    enabled: true
    find-already-discovered:
      loot-tables: default
      villager-trade: false
  void-damage-amount: 4.0
  void-damage-min-build-height-offset: -64.0
  water-over-lava-flow-speed: 5
feature-seeds:
  generate-random-seeds-for-all: false
fishing-time-range:
  maximum: 500
  minimum: 100
fixes:
  disable-unloaded-chunk-enderpearl-exploit: true
  falling-block-height-nerf: 3
  fix-items-merging-through-walls: true
  prevent-tnt-from-moving-in-water: true
  split-overstacked-loot: true
  tnt-entity-height-nerf: 5
hopper:
  cooldown-when-full: true
  disable-move-event: true
  ignore-occluding-blocks: true
lootables:
  auto-replenish: false
  max-refills: -1
  refresh-max: 2d
  refresh-min: 12h
  reset-seed-on-fill: true
  restrict-player-reloot: true
  restrict-player-reloot-time: disabled
retain-unlooted-shulker-box-loot-table-on-non-player-break: true
maps:
  item-frame-cursor-limit: 32
  item-frame-cursor-update-interval: 40
max-growth-height:
  bamboo:
    max: 16
    min: 11
  cactus: 3
  reeds: 3
misc:
  alternate-current-update-order: HORIZONTAL_FIRST_OUTWARD
  disable-end-credits: true
  disable-relative-projectile-velocity: true
  disable-sprint-interruption-on-attack: true
  light-queue-size: 100
  max-leash-distance: 6
  redstone-implementation: FAST
  shield-blocking-delay: 2
  update-pathfinding-on-block-update: false
scoreboards:
  allow-non-player-entities-on-scoreboards: false
  use-vanilla-world-scoreboard-name-coloring: false
spawn:
  allow-using-signs-inside-spawn-protection: false
  spawn-protection: 0
  spawn-allowed-players: 5
  disable-player-drops: true
tick-rates:
  behavior:
    villager:
      validatenearbypoi: -1
  container-update: 3
  dry-farmland: 5
  grass-spread: 5
  mob-spawner: 40
  sensor:
    villager:
      secondarypoisensor: 80
  wet-farmland: 5
unsupported-settings:
  disable-world-ticking-when-empty: true
  fix-invulnerable-end-crystal-exploit: true
  disable-unloaded-chunk-enderpearl-exploit: true
  optimize-enderdragon: true
  limit-entity-collisions: true
